Fix post testing

diff --git a/cron_checkip/task b/cron_checkip/task
--- a/cron_checkip/task
+++ b/cron_checkip/task
@@ -1,32 +1,50 @@
 #!/bin/bash
 #
-#
 # Title: task
 #
 # Description:
 #   Script intended for execution in cron to detect and send alerts of external
-#   (public) IP address changes. Uses jjo93sa/ip-utils to retrieve IP address
-#   from ipinfo.io and pushover to send push notifications with pushover.net.
-#   If a new Ip address is detected, a push notification is set and an attempt
-#   is made to update a DuckDNS domain. All these services require user and/or
-#   service tokens, which must be set in the environment file, checkip.env.
+#   (public) IP address changes. Uses scripts from the repositories listed in
+#   the "Dependencies" section to provide most of the functionality.
 #
-#   Docker container cron-template requires a script called task to implement
-#   the function that is to be executed by cron. This script fulfils that
-#   requirement.
+#   Notifications are provided by pushover.net; IP address detection by
+#   ipinfo.io; and, dynamic DNS services by duckdns.org.
+#
+#   An example implementation of this service can be found in Docker image
+#   r.j2o.it/cron_checkip, which has been built to execute this script every
+#   5 minutes. r.j2o.it/cron_checkip is based on image r.j2o.it/cron, which
+#   requires a script called "task" to define the process to be executed by
+#   cron. This script fulfils that role. Docker files for both images may be
+#   found at: https://github.com/jjo93sa/dockerfiles.git. Also in that repo
+#   is a template environment file (checkip.env) for your user and access
+#   tokens from the three dependency services.
+#
+# Dependencies:
+#   Requires scripts from the following repositories:
+#
+#   - https://github.com/jjo93sa/ip-utils.git
+#   - https://github.com/jjo93sa/notification-utils.git
+#   - https://github.com/jjo93sa/script-utils.git
+#
+#   Which themselves require accounts with:
+#
+#   - ipinfo.io
+#   - duckdns.org
+#   - pushover.net
 #
 # Usage:
 #   Run this script in a crontab, for example, using a "concrete" instance of
-#   Docker container cron-template.
+#   image r.j2o.it/cron (see https://github.com/jjo93sa/dockerfiles.git).
 #
-# Maintainer: dr.j.osborne@gmail.com
+# Maintainer:
+#   James Osborne, dr.j.osborne@gmail.com
 #
-# License: MIT, see LICENSE file in repository root
+# License:
+#   MIT, see LICENSE file in repository root
 #
 
 : ${REPEAT=5}
-: ${DELAY=30}
-COUNT=0
+: ${DELAY=20}
 
 #TODO: Should perhaps convert these to tests to ensure that the files exist
 
@@ -47,83 +65,47 @@ then
    exit 0
 fi
 
-until (( COUNT > REPEAT ))
-do
-    (( COUNT++ ))
+# Get the current external IP address using function in get_ip_info.
+# get_pub_ip_retry repeatedly attempts to get the IP address from ipinfo.io
+# It will either return a well-formatted address and a zero exit code, or it
+# will return an empty string and non-zero code.
+if IP_ADDRESS=$(get_pub_ip_retry $REPEAT $DELAY)
+then
+    # We have a good IP address
+    # Get the IP address from the RUN_FILE, where it was stored at last change
+    OLD_IP_ADDRESS=$(grep -Eo '[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}' $RUN_FILE)
 
-    ALERT_MSG="$COUNT: "
+    # Set OLD_IP_ADDRESS to 0.0.0.0 if no address found in RUN_FILE, e.g start-up
+    [[ -z "$OLD_IP_ADDRESS" ]] && OLD_IP_ADDRESS="0.0.0.0"
 
-    # Get the current external IP address using function in get_external_ip.sh
-    IP_ADDRESS=$(get_external_ip)
-
-    CHECK_IP_EXIT_STATUS=$?
-
-    # IP_ADDRESS might still be improperly set
-    #+ Check for a non zero exit status from get_external_ip and check that
-    #+ IP_ADDRESS isn't empty
-    if [ $CHECK_IP_EXIT_STATUS -ge 1 ] || [ -z "$IP_ADDRESS" ]
+    # Take action if there's a difference between the old and new addresses:
+    if [ "$IP_ADDRESS" != "$OLD_IP_ADDRESS" ]
     then
-        # Build a message string with the failure date time and the exit code
-        ALERT_MSG+="IP address detection failed: ipinfo returned $CHECK_IP_EXIT_STATUS"
+        ALERT_MSG="IP change from $OLD_IP_ADDRESS to $IP_ADDRESS"
 
-        # Since we didn't get an IP address, log it as 0.0.0.0 so we get a good
-        # message with a proper IP when ipinfo next works
-        update_run "0.0.0.0"
-    else
-        # Get the IP address from the RUN_FILE, where it was stored at last change
-        OLD_IP_ADDRESS=$(grep -Eo '[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}' $RUN_FILE)
-
-        # Set OLD_IP_ADDRESS to 0.0.0.0 if no address found in RUN_FILE, e.g start-up
-        [[ -z "$OLD_IP_ADDRESS" ]] && OLD_IP_ADDRESS="0.0.0.0"
-
-        # Now the smart stuff, log an IP address change, if there's a difference
-        if [ "$IP_ADDRESS" != "$OLD_IP_ADDRESS" ]
+        # Update DNS:
+        if update_duckdns_retry "$DOM_TO_CHECK" "$IP_ADDRESS" "$REPEAT" "$DELAY"
         then
-            # We have a new IP address
-
-            # Build a message string with the date time and the new IP
-            ALERT_MSG+="IP change from $OLD_IP_ADDRESS to $IP_ADDRESS"
-
-            # Now update DuckDNS
-            #TODO: If $DOM_TO_CHECK isn't set, let's not do this m'k
-            DNS_RET=$(updatedns $DOM_TO_CHECK $IP_ADDRESS)
-
-            # Test curl return - IF was good should have "OK200"
-            if [[ "$DNS_RET" != "OK200" || "$?" -gt 0 ]]
-            then
-                ALERT_MSG+=" but DuckDNS NOT updated $DNS_RET"
-            else
-                ALERT_MSG+=" and DuckDNS returned $DNS_RET"
-            fi
-
-            # And update the run file with the new address, timestamp
-            #update_run_file "$IP_ADDRESS"
-            update_run "$IP_ADDRESS"
+            ALERT_MSG+=" & Duck DNS updated successfully"
         else
-            # We haven't got a new IP address
-            ALERT_MSG=
-
-            # Just update the timestamp of the run file so we know we've run
-            update_run
+            ALERT_MSG+=" & Duck DNS update failed"
         fi
 
-        # Break here--we've either got the same IP or got a new IP and don't
-        # need to loop further
-        break
+        # Store the new IP address in the $RUN_FILE for the next execution
+        update_run "$IP_ADDRESS"
+
+        # Alert the user:
+        echo "$ALERT_MSG" | write_log | pushover
+    else
+        # Same IP hasn't changed, so just record execution of this script
+        update_run
     fi
-
-    sleep $DELAY
-done
-
-# If we've got an ALERT message, handle it
-if [ -n "$ALERT_MSG" ]
-then
-    # Send the new IP message to push over
-    #pushover "$ALERT_MSG"
-
-    # And update the log file
-    #log_message "$ALERT_MSG"
-    echo "$ALERT_MSG" | write_log | pushover
+else
+    # No IP was retrieved, we might consider alerting the user, but for now log
+    # a message and update the script execution time
+    #ASSUME exit code here is that of the call to get_pub_ip_retry()
+    write_log "NO IP address retrieved by get_pub_ip_retry $?"
+    update_run
 fi
 
 # Delete old log files
